openapi: "3.0.0"
info:
  version: 1.0.0
  title: Laravel API
  license:
    name: MIT
servers:
  - url: /api
paths:
  /users:
    get:
      summary: List all users
      operationId: listUsers
      tags:
        - users
      parameters:
        - name: include
          in: query
          description: Include relations of user
          required: false
          schema:
            type: string
      responses:
        "200":
          description: A paged array of users
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Users"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  schemas:
    User:
      required:
        - id
        - first_name
        - last_name
        - email
        - phone
        - created
        - updated
      properties:
        id:
          type: string
          format: uuid
        first_name:
          type: string
        last_name:
          type: string
        email:
          type: string
        phone:
          type: string
        created:
          type: string
          format: date-time
        updated:
          type: string
          format: date-time
    Users:
      type: array
      items:
        $ref: "#/components/schemas/User"
    Error:
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
